name: sum
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=22.3
  # core packages
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - mlflow=1.2
  - numpy=1.23
  - pandas=1.5
  - nltk
  # utils
  - pyyaml
  - notebook
  - tqdm
  # qa
  - pre-commit
  - flake8
  - black
  - isort
  - pip:
    - transformers==4.25
    - tokenizers==0.13
    - sentencepiece==0.1.97
    - evaluate
    - absl-py
    - rouge-score
